 [
    {
        "key": "datr",
        "value": "1pIGaZ_coSqaqZwElT7oJV4q",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "sb",
        "value": "1pIGaVHpT1XzrqT2kltWT5Tt",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "c_user",
        "value": "61581960597639",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "xs",
        "value": "13%3AE298q5cowrZavA%3A2%3A1762039158%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "locale",
        "value": "en_US",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "pas",
        "value": "61581960597639%3Ak8xL3aVYps",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "ps_l",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "ps_n",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B736x393x2.75",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "fr",
        "value": "0B2g52msABSx21CuR.AWdKTjhD7x04flsw_bh5OkdGmHhZp2RIu63m0dUai55a3aqWZxM.BpBpLW..AAA.0.0.BpByir.AWfe0bKIkebczRhqi19Y9me7bwY",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "fbl_st",
        "value": "101525192%3BT%3A29367947",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2971%3Btimestamp%3A1762076843",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-11-02T09:47:28.040Z",
        "lastAccessed": "2025-11-02T09:47:28.040Z"
    }
]
